### ISSUE TITLE
Recommendation?

### ISSUE THREAD

**Issue by ahttraga** [milkovsky/Linux-on-Lenovo-Slim-7-Carbon-AMD#1]
I'm thinking about getting the same system for use with linux only.  Would you still recommend it despite all the issues?  How do you manage without suspend functionality?  Do you use Windows as well?  Do you have any issues with [screen flickering](https://www.reddit.com/r/AMDLaptops/comments/r39hji/lenovo_yoga_slim_7_carbon_14_oled_hardware_zone/)?

**Comment by ahttraga** [comment]
Have you tried a USB stick with [MX Linux Advanced Hardware Support](https://mxlinux.org/download-links/)?

**Comment by ahttraga** [comment]
Also looking at the [Arch forums](https://wiki.archlinux.org/title/Laptop/Lenovo#Yoga_Series), it seems the BIOS version is important for sleep with the Lenovo Yoga Slim 7 Pro (AMD Ryzen 7):

> BIOS version G7CN16WW (and possibly above) needed for S3 sleep to work.

**Comment by milkovsky** [comment]
> I'm thinking about getting the same system for use with linux only. Would you still recommend it despite all the issues?

As there are still open issues I can not recommend you this laptop. In addition Lenovo has better Linux support on other laptops. This is a choice, that you should make. I personally will keep using the laptop with Linux, because I like the hardware and I hope, that I will find solutions soon :)

> How do you manage without suspend functionality?

Sad, but I shutdown the system every time. Still looking for a fix.

> Do you use Windows as well?

Yes. I have a dual-boot. Windows works 100% stable.

> Do you have any issues with screen flickering?

No, have not noticed anything. Screen is great, multi-touch works as well.
On the other hand I had another issue. Laptop is not stable (wobbles) on a flat area (like table). I am in the process of getting a replacement.

> Have you tried a USB stick with MX Linux Advanced Hardware Support?

No. I should try this out.

> Also looking at the Arch forums, it seems the BIOS version is important for sleep with the Lenovo Yoga Slim 7 Pro (AMD Ryzen 7):

Thank you for pointing this. I also saw a post somewhere, that a BIOS update might help. I am afraid to mess up everything by a BIOS updates, I have never done this before.

**Comment by milkovsky** [comment]
you can also check this thread: https://www.reddit.com/r/linuxhardware/comments/qxtson/lenovo_slim_7_carbon_14_amd_linux_support/

**Comment by ahttraga** [comment]
Here are some promising links about fixing *s2idle* problems on the same processor but different laptop:
- [One-Line Linux Patch Fixes AMD s2idle Failures For Some Ryzen Laptops](https://www.phoronix.com/scan.php?page=news_item&px=AMD-s2idle-One-Line-Fix)
- [s2idle fails when battery power on 5800U](https://gitlab.freedesktop.org/drm/amd/-/issues/1799)

And the brightness problem:
- [r/AMDLaptops "After updating to linux 5.15, my brightness controls aren't working? (ryzen 5800u)"](https://www.reddit.com/r/AMDLaptops/comments/qst0fm/after_updating_to_linux_515_my_brightness/)

**Comment by oppsig** [comment]
Im really liking this laptop even though speaker issues are there. I would say speakers on linux is unusable so far.
The screen is really nice, and 90 Hz, but since it is a oled it is pretty reflective in very bright environments. Performance and size vs weight ratio is impressive, docking with a usb-c dock works fine. I was debating if I should wait for z13 to get usb 4 since this does not have thunderbolt, but right now I only have the need for dual 1920x1200@60. It has DP 1.4 alt mode at least.

**Comment by milkovsky** [comment]
@oppsig which configuration have you got? Have you got an integrated graphic card?
Also which Linux distribution are you using?

**Comment by oppsig** [comment]
@milkovsky I'm running archlinux with sway. I do not have the nvidia mx 450. I did try latest ubuntu to see if sound was working there. Wifi support is in the kernel. I'll probably try to compile linux-next kernel to se if sound is supported there next.

**Comment by milkovsky** [comment]
Some updates (Tested on PopOS 22.04 LTS Kernel 5.18.10, Ubuntu 22.04 LTS):

> [One-Line Linux Patch Fixes AMD s2idle Failures For Some Ryzen Laptops](https://www.phoronix.com/scan.php?page=news_item&px=AMD-s2idle-One-Line-Fix)
>  [s2idle fails when battery power on 5800U](https://gitlab.freedesktop.org/drm/amd/-/issues/1799)

Suspend works stable from the box.

> And the brightness problem:
>    [r/AMDLaptops "After updating to linux 5.15, my brightness controls aren't working? (ryzen 5800u)"](https://www.reddit.com/r/AMDLaptops/comments/qst0fm/after_updating_to_linux_515_my_brightness/)

Both brightness controls and automatic brightness work stable from the box as well.

As for the initial issue, here are my personal cons/pros for this laptop:
Pros:
- lightweight and portable
- great performance
- great screen
- comfortable keyboard, toutchpad 
- the laptop works pretty stable.
- Battery life is good (as for Linux). Around 5-6h in casual use.
- All other things work stable, see the [README.md](https://github.com/milkovsky/Linux-on-Lenovo-Slim-7-Carbon-AMD/blob/main/README.md).
- nice design

Cons:
- 2 out of 4 speakers do not work. This is the **main con** for me, until this issue is open, I could not recommend this laptop. See https://github.com/milkovsky/Linux-on-Lenovo-Slim-7-Carbon-AMD/issues/2
- Laptop gets warm even after casual use (surfing, watching videos, lite coding).
- RAM is not upgradable.

I am closing this issue, feel free to open new one if needed.

**Comment by milkovsky** [comment]
Some personal opinion. I have tested the next operation systems on this laptop: Fedora, Ubuntu, Pop!_OS.
Out of the box Pop!_OS showed the most stable functionality (including suspend on lid close) overall and most importantly the longest battery live.
